#!/usr/bin/env bash

echo "------------------"
git status
echo "git status success"
echo "------------------"

git pull
echo "git pull success"
echo "------------------"

git add .
echo "git add success"
echo "------------------"

git commit -m "update"
echo "git commit success"
echo "------------------"

git push
echo "git push success"
echo "------------------"
