apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: myapp
    type: front-end

--------------------------------------------------------

kubectl create -f service-definition.yml

kubectl get services